import type { Metadata } from "next";
import {Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sections/Navbar";

const MontserratFont = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${MontserratFont.variable} antialiased bg-[#111015] text-[#FEFEFE]`}
      >
        <div className="sticky inset-0">
        <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
